# 02 - Quatérnios

Quatérnios possuem vários usos, porém aqui vamos nos concentrar nos recursos de realizar rotações no espaço 3D. A construção matemática do quatérnio é em geral expressa da seguinte forma:

$$
q = q_r + q_i \mathbf{i} + q_j \mathbf{j} + q_k \mathbf{k}
$$

Podemos calcular o comprimento de um quatérnio com a seguinte fórmula:

$$
|q| = \sqrt{q\bar{q}} = \sqrt{q_i^2 + q_j^2 + q_k^2 + q_r^2}
$$

A multiplicação de quatérnios é um recurso que permite fazer as operações de rotação. Uma das formas de fazer essa opção é por um processo distributivo:

$$
pq = (p_r + p_i i + p_j j + p_k k)(q_r + q_i i + q_j j + q_k k) \\
= (p_r q_r - p_i q_i - p_j q_j - p_k q_k) + (...)i + (...)j + (...)k
$$

Outra forma é usando os recursos de multiplicação escalar e vetorial:

$$
pq = p_r q_r - \mathbf{p} \cdot \mathbf{q} + p_r \mathbf{q} - q_r \mathbf{p} + \mathbf{p} \times \mathbf{q}
$$

Não se esqueça que a ordem da multiplicação é importante, e o cuidado que você deve ter é na multiplicação dos imaginários. Assim siga sempre a seguinte regra:

$$
\mathbf{i}^2 = \mathbf{j}^2 = \mathbf{k}^2 = -1, \mathbf{ijk} = -1 \\
\mathbf{ij} = \mathbf{k}, \quad \mathbf{jk} = \mathbf{i}, \quad \mathbf{ki} = \mathbf{j} \\
\mathbf{ji} = -\mathbf{k}, \quad \mathbf{kj} = -\mathbf{i}, \quad \mathbf{ik} = -\mathbf{j}
$$

Rotações podem ser calculadas no espaço 3D pelas matrizes de rotação, que usam coordenadas de Euler diretamente. Como visto em aula, essas matrizes têm suas limitações:

$$
\mathbf{R}_{x,\theta} = \begin{bmatrix}
1 & 0 & 0 \\
0 & \cos\theta & -\sin\theta \\
0 & \sin\theta & \cos\theta
\end{bmatrix}
\quad
\mathbf{R}_{y,\theta} = \begin{bmatrix}
\cos\theta & 0 & \sin\theta \\
0 & 1 & 0 \\
-\sin\theta & 0 & \cos\theta
\end{bmatrix}
\quad
\mathbf{R}_{z,\theta} = \begin{bmatrix}
\cos\theta & -\sin\theta & 0 \\
\sin\theta & \cos\theta & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

Uma alternativa é através de quatérnios. Para isso se pode criar o quatérnio de rotação com a seguinte fórmula:

$$
q = \cos \left(\frac{\theta}{2}\right) + \sin \left(\frac{\theta}{2}\right) u_x \mathbf{i} + \sin \left(\frac{\theta}{2}\right) u_y \mathbf{j} + \sin \left(\frac{\theta}{2}\right) u_z \mathbf{k}
$$

Existem duas formas de aplicar a rotação por quatérnios, uma é multiplicando o vetor que se deseja rotacionar pelo quatérnio e depois pelo seu conjugado:

$$
rot(\mathbf{v}) = q \cdot \mathbf{v} \cdot q^{-1}
$$

A outra forma é colocar os valores do quatérnio em uma matriz e então multiplicar o vetor. A matriz de rotação usando quatérnios usa a seguinte construção:

$$
R = \begin{bmatrix}
1 - 2(q_y^2 + q_z^2) & 2(q_x q_y - q_z q_r) & 2(q_x q_z + q_y q_r) & 0 \\
2(q_x q_y + q_z q_r) & 1 - 2(q_x^2 + q_z^2) & 2(q_y q_z - q_x q_r) & 0 \\
2(q_x q_z - q_y q_r) & 2(q_y q_z + q_x q_r) & 1 - 2(q_x^2 + q_y^2) & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

Vamos verificar se os quatérnios funcionam mesmo.

a) Assuma um ponto (0, 1, 0), faça uma rotação por Z de 45° usando a matriz de rotação por coordenadas de Euler e depois por quatérnios, verifique se os resultados coincidem.

In [20]:
import math
import numpy as np

angle = 45
radians = math.radians(angle)

point = np.array([[0],[1],[0]])

Z_rotation = np.array([
    [math.cos(radians), -math.sin(radians), 0],
    [math.sin(radians), math.cos(radians), 0],
    [0, 0, 1]
])

X_rotation = np.array([
    [1, 0, 0],
    [0, math.cos(radians), -math.sin(radians)],
    [0, math.sin(radians), math.cos(radians)]
])

Y_rotation = np.array([
    [math.cos(radians), 0, math.sin(radians)],
    [0, 1, 0],
    [-math.sin(radians), 0, math.cos(radians)]
])

Y_rotation @ X_rotation @ Z_rotation @ point

array([[-0.14644661],
       [ 0.5       ],
       [ 0.85355339]])

In [17]:
angle = 45
radians = math.radians(angle)

point = np.array([[0],[1],[0],[1]])

def quaternion_rotation_matrix(x: float, y: float, z: float, t: float):
            """
            A função quaternion_rotation_matrix usa 
            eixo da rotação (x, y, z), em conjunto 
            com o valor em radianos para theta
            para criar a matriz de rotação.
            """

            def generate_quaternion(x: float, y: float, z: float, theta: float):
                """
                A função generate_quaternion usa o 
                eixo da rotação (x, y, z) em conjunto
                com o valor em radianos para theta
                para criar o quatérnio que irá compor a 
                matriz de rotação.

                um quatérnio [qi, qj, qk, qr] é, na
                prática, o vetor [
                    ux*sin(theta/2),
                    uy*sin(theta/2),
                    uz*sin(theta/2),
                    cos(theta/2)
                ]

                sendo ux, uy e uz os versores do eixo
                (vetor [x, y, z] divido pela norma). 
                """
                vector = np.array([x, y, z])
                norm = np.linalg.norm(vector)

                # se a norma do vetor é zero, não
                # há rotação, e o se usa o quatérnio 1,
                # equivalente a identidade.
                if norm == 0:
                    return (0, 0, 0, 1)
                
                normalized_vector = vector / norm
                ux, uy, uz = normalized_vector

                return (
                    ux * math.sin(theta/2),
                    uy * math.sin(theta/2),
                    uz * math.sin(theta/2),
                    math.cos(theta/2)
                )
            
            qi, qj, qk, qr = generate_quaternion(x, y, z, t)
            
            return np.array([
                [1 - 2*(qj**2 + qk**2), 2*(qi*qj - qk*qr), 2*(qi*qk + qj*qr), 0],
                [2*(qi*qj + qk*qr), 1 - 2*(qi**2 + qk**2), 2*(qj*qk - qi*qr), 0],
                [2*(qi*qk - qj*qr), 2*(qj*qk + qi*qr), 1 - 2*(qi**2 + qj**2), 0],
                [0, 0, 0, 1]
            ])

quaternion_Z_rotation = quaternion_rotation_matrix(0, 0, 1, radians)
quaternion_Z_rotation @ point

array([[-0.70710678],
       [ 0.70710678],
       [ 0.        ],
       [ 1.        ]])

b) Continue a rotação do ponto acima, porém agora além da rotação em Z, faça também uma rotação de 45° em X.

In [18]:
quaternion_X_rotation = quaternion_rotation_matrix(1, 0, 0, radians)
quaternion_X_rotation @ quaternion_Z_rotation @ point

array([[-0.70710678],
       [ 0.5       ],
       [ 0.5       ],
       [ 1.        ]])

c) Continue mais uma vez a rotação do ponto, agora com mais uma rotação em Y de 45°.

In [19]:
quaternion_Y_rotation = quaternion_rotation_matrix(0, 1, 0, radians)
quaternion_Y_rotation @ quaternion_X_rotation @ quaternion_Z_rotation @ point

array([[-0.14644661],
       [ 0.5       ],
       [ 0.85355339],
       [ 1.        ]])